site_name: Материалы по проектированию и управлению качеством
site_url: https://maximsamokhval.github.io/archiDocs/
site_author: Maxim Samokhval
site_description: Полезные статьи и документация по разработке на 1С:Предприятие
repo_name: maximsamokhval/archiDocs
repo_url: https://github.com/maximsamokhval/archiDocs/
edit_uri: edit/main/docs

extra:
  generator: true
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/maksym_samokhval
      name: Telegram me
    - icon: fontawesome/brands/github
      link: https://github.com/maximsamokhval

copyright: Copyright &copy; 2022 Maxim Samokhval

theme:
  name: material

  features:
    - toc.integrate
    - navigation.top
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    #- navigation.expand
    - header.autohide
    - announce.dismiss
    - search.highlight
    - search.suggest
    - search.share

  palette:
    - scheme: default
      primary: teal
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  language: ru
  font:
    text: Ubuntu
    code: Roboto Mono
  icon:
    logo: material/library-shelves
    repo: fontawesome/brands/git
  plugins:
    - tags
    - social
    - rss
    - search:
        lang:
          - en
          - ru

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - tables
  - meta
  - md_in_html
  - pymdownx.betterem
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        # Mermaid diagrams
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets
  - toc:
      permalink: true
extra_javascript:
  - optionalConfig.js
  - https://unpkg.com/mermaid@8.8.4/dist/mermaid.min.js
  - extra-loader.js
nav:
  - Начало: index.md
  - 1С Разработка:
      - Моделирование: 1CDevelopment/modeling.md
      - Проектирование: 1CDevelopment/rec_of_structure.md
      - Ограничения: 1CDevelopment/Vliyanie_ogranichenij_dliny_klyucha_indeksov.md
  - Development:
      - Software Estimation: Development/index.md
  - Architecture:
      - Шаблоны: Templates/InterviewQuestions.md
      - Материалы: Architecture/index.md
      - Заметки: Architecture/Notes/index.md
      - Документы:
          - Список документов: Architecture/Documents/index.md
          - Документ о концепции и границах проекта: Architecture/Documents/Документ-о-концепции-и-границах-проекта.md
      - NFR:
          - NFR template: Architecture/NFR/Template/index.md
      - Атрибуты качества:
          - Список атрибутов: Architecture/QualityAttributes/index.md
          - Ограничения: Architecture/QualityAttributes/constraint.md
          - Внешние аттрибуты качества:
              - Architecture/QualityAttributes/ExtrenalAttributes/availability.md
              - Architecture/QualityAttributes/ExtrenalAttributes/installability.md
              - Architecture/QualityAttributes/ExtrenalAttributes/integrity.md
              - Architecture/QualityAttributes/ExtrenalAttributes/interoperability.md
              - Architecture/QualityAttributes/ExtrenalAttributes/performance.md
              - Architecture/QualityAttributes/ExtrenalAttributes/reliability.md
              - Architecture/QualityAttributes/ExtrenalAttributes/robustness.md
              - Architecture/QualityAttributes/ExtrenalAttributes/safety.md
              - Architecture/QualityAttributes/ExtrenalAttributes/secutity.md
              - Architecture/QualityAttributes/ExtrenalAttributes/usability.md
          - Внутренние аттрибуты качества:
              - Architecture/QualityAttributes/InternalAttributes/modifiability.md
              - Architecture/QualityAttributes/InternalAttributes/efficiency.md
              - Architecture/QualityAttributes/InternalAttributes/portability.md
              - Architecture/QualityAttributes/InternalAttributes/reusability.md
              - Architecture/QualityAttributes/InternalAttributes/scalability.md
              - Architecture/QualityAttributes/InternalAttributes/verifyability.md

      - RFC Template:
          - Шаблон: Architecture/RFC/rfc-template.md
          - RFC taskManager: Architecture/RFC/rfc-taskManager.md
  - Wiki:
      - Терминология:
          - Ортогональность: Wiki/orto.md
          - Глоссарий: Wiki/glossary.md
